# Generated by Django 5.1.7 on 2025-03-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_fooditem_chef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image_url',
            field=models.URLField(blank=True, default='https://t3.ftcdn.net/jpg/02/48/42/64/360_F_248426448_NVKLywWqArG2ADUxDq6QprtIzsF82dMF.jpg'),
        ),
    ]
